/// Conformance suite for ic402's Ed25519 verifier (src/ic402/Ed25519.mo, vendored in 2.16.1).
///
/// WHY THIS EXISTS. Before 2.16.1 ic402 verified with `mo:ed25519` 0.1.0, whose
/// `bitrightshift(0, n)` returned 2^n − 1. That corrupted its base-point multiply whenever a
/// scalar's top 8-bit window (after the carry from below) was zero, so it REFUSED about 1 valid
/// signature in 32 (S < 2^247, plus a thin band just above), ACCEPTED an invalid partner
/// (S + 2^256 mod L) of each of those, and signed and derived public keys wrongly about 1 time
/// in 32. Nothing in ic402's own tests caught it, because they signed and verified with the same
/// broken library.
///
/// So every expectation here comes from OUTSIDE ic402: RFC 8032, Wycheproof, ed25519-speccheck,
/// and vectors generated by OpenSSL and noble. Provenance: test/fixtures/ed25519/README.md.
///
/// POLICY (RFC 8032 strict, cofactorless — the cases RFC 8032 leaves open are decided here):
///   - S must be canonical: 0 <= S < L.
///   - A and R must be canonical point encodings: y < p, a square root exists, no negative zero.
///   - The equation is cofactorless: [S]B = R + [k]A, matching OpenSSL.
///   - Small-order public keys are REFUSED (OpenSSL accepts them). A small-order A admits one
///     "signature" valid for every message — see the universal-forgery test below.
///   - Small-order or mixed-order R is NOT separately refused; it simply has to satisfy the
///     equation, which no forger can arrange without the key.
///   - Every malformed input returns false. Nothing traps.
import Ed25519 "../src/ic402/Ed25519";
import V "fixtures/ed25519/Vectors";
import Blob "mo:base/Blob";
import Array "mo:base/Array";
import Nat8 "mo:base/Nat8";
import Debug "mo:base/Debug";
import Text "mo:base/Text";
import { test; suite } "mo:test";

func verify(sig : Blob, msg : Blob, pub : Blob) : Bool = Ed25519.verify(sig, msg, pub);

func b(bytes : [Nat8]) : Blob = Blob.fromArray(bytes);
func cat(x : Blob, y : Blob) : Blob = Blob.fromArray(Array.append(Blob.toArray(x), Blob.toArray(y)));
func zeros(n : Nat) : Blob = Blob.fromArray(Array.tabulate<Nat8>(n, func(_) = 0));

suite("RFC 8032 section 7.1", func() {
  for (v in V.rfc8032.vals()) {
    test(v.name # ": the signature verifies", func() {
      assert verify(v.sig, v.msg, v.pub);
    });
    test(v.name # ": the vendored signer reproduces the RFC signature and public key", func() {
      // ic402's tests sign fixtures with this signer, so pin that it is RFC-exact.
      assert Ed25519.publicKey(v.seed) == v.pub;
      assert Ed25519.sign(v.seed, v.msg) == v.sig;
    });
  };
});

suite("Wycheproof ed25519_test.json — all 151 match the expected result", func() {
  // Per-flag, so a failure names its category. The count check catches a generator that
  // silently drops vectors.
  let expected : [(Text, Nat)] = [
    ("Valid", 18), ("Ktv", 38), ("TinkOverflow", 32), ("InvalidSignature", 20),
    ("TruncatedSignature", 3), ("SignatureWithGarbage", 5), ("CompressedSignature", 4),
    ("InvalidEncoding", 22), ("SignatureMalleability", 8), ("InvalidKtv", 1),
  ];
  for ((flag, count) in expected.vals()) {
    test(flag # " (" # debug_show(count) # " vectors)", func() {
      var seen = 0;
      var mismatches = 0;
      for (v in V.wycheproof.vals()) {
        if (v.flag == flag) {
          seen += 1;
          if (verify(v.sig, v.msg, v.pub) != v.valid) {
            Debug.print("  MISMATCH tcId " # debug_show(v.tcId) # " expected " # debug_show(v.valid));
            mismatches += 1;
          };
        };
      };
      assert seen == count;
      assert mismatches == 0;
    });
  };
  test("the fixture holds exactly 151 vectors", func() { assert V.wycheproof.size() == 151 });
});

suite("ed25519-speccheck — the policy RFC 8032 leaves open, one case at a time", func() {
  // (expected, reason). OpenSSL 3.6.3 gives T,T,T,T,F,F,F,F,F,F,F,T — this policy is STRICTER
  // than OpenSSL in cases 0, 1 (small-order A) and 11 (non-canonical A), and agrees elsewhere.
  let policy : [(Bool, Text)] = [
    (false, "0: small-order A and R — refused (small-order public key)"),
    (false, "1: small-order A — refused (small-order public key; OpenSSL accepts)"),
    (true,  "2: small-order R, mixed-order A — accepted (both equations hold; R is not screened)"),
    (true,  "3: mixed-order A and R — accepted (both equations hold)"),
    (false, "4: holds only under the COFACTORED equation — refused (cofactorless)"),
    (false, "5: holds only cofactored with a pre-reduced [8h] — refused (cofactorless)"),
    (false, "6: S > L — refused (non-canonical S)"),
    (false, "7: S >> L — refused (non-canonical S)"),
    // Cases 8-11 encode (0, -1) as "negative zero" (x = 0 with the sign bit set).
    (false, "8: negative-zero R, reduced for hash — refused (canonical R required)"),
    (false, "9: negative-zero R, not reduced for hash — refused (canonical R required)"),
    (false, "10: negative-zero A, reduced for hash — refused (canonical A required)"),
    (false, "11: negative-zero A, not reduced for hash — refused (OpenSSL accepts)"),
  ];
  assert V.speccheck.size() == policy.size();
  for (c in V.speccheck.vals()) {
    let (want, why) = policy[c.index];
    test(why, func() { assert verify(c.sig, c.msg, c.pub) == want });
  };
});

suite("regressions from the mo:ed25519 0.1.0 defect", func() {
  for (r in V.regressions.vals()) {
    let what = if (r.valid) "accepted" else "REFUSED";
    test(r.name # " — " # what, func() { assert verify(r.sig, r.msg, r.pub) == r.valid });
  };
});

suite("policy vectors — each is refused by exactly one check", func() {
  // Built under the RFC 8032 TEST 1 key so that ONE check stands between each and acceptance:
  // the y < p decode check, then the y half and the x half of the final comparison. The
  // speccheck and Wycheproof sets do not pin these on their own (an adversarial review found
  // each check could be deleted with every other test still green). Construction: policy.json.
  for (v in V.policy.vals()) {
    test(v.name # " — REFUSED", func() { assert verify(v.sig, v.msg, v.pub) == v.valid });
  };
});

suite("small-order public keys", func() {
  // With A = the identity (encoded y = 1), [k]A = O for every k, so the cofactorless equation
  // [S]B = R + [k]A collapses to [S]B = R. Taking S = 0 and R = O gives ONE signature that
  // "verifies" for EVERY message. Refusing small-order keys is what stops it.
  let identity : Blob = "\01\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00";
  let universal = cat(identity, zeros(32)); // R = O, S = 0
  test("the identity key's universal forgery is refused, for several messages", func() {
    assert not verify(universal, b([]), identity);
    assert not verify(universal, b([1, 2, 3]), identity);
    assert not verify(universal, Text.encodeUtf8("transfer everything"), identity);
  });
});

suite("total: every malformed input returns false and nothing traps", func() {
  // A trap here would abort the whole file, so reaching each assert IS the no-trap proof.
  let v = V.rfc8032[0];
  let sig = v.sig;
  let pub = v.pub;
  let msg = v.msg;
  let rOf = func(s : Blob) : [Nat8] = Array.subArray(Blob.toArray(s), 0, 32);
  let sOf = func(s : Blob) : [Nat8] = Array.subArray(Blob.toArray(s), 32, 32);

  // Encodings computed from the curve definition (see the PR): y = 2 has no square root.
  let offCurve : Blob = "\02\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00";
  let negZero : Blob = "\01\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\80";
  let yEqP : Blob = "\ed\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\7f";
  let yMax : Blob = "\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\7f";
  let sEqL : Blob = "\ed\d3\f5\5c\1a\63\12\58\d6\9c\f7\a2\de\f9\de\14\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\10";
  let sMax : Blob = "\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff\ff";

  test("the unmodified vector verifies (control)", func() { assert verify(sig, msg, pub) });

  test("wrong signature lengths", func() {
    for (n in [0, 1, 32, 63, 65, 96, 128].vals()) {
      assert not verify(Blob.fromArray(Array.tabulate<Nat8>(n, func(i) = if (i < 64) Blob.toArray(sig)[i] else 0)), msg, pub);
    };
  });
  test("wrong public-key lengths", func() {
    for (n in [0, 1, 31, 33, 64].vals()) {
      assert not verify(sig, msg, Blob.fromArray(Array.tabulate<Nat8>(n, func(i) = if (i < 32) Blob.toArray(pub)[i] else 0)));
    };
  });
  test("non-canonical S: the valid S + L is refused (it verifies iff the S < L check is gone)", func() {
    // S + L satisfies the curve equation exactly as S does, so only the canonical-S check can
    // refuse it. This is the input that proves the check exists; S = L and S = 2^256 - 1 below
    // are refused by the equation anyway and only prove nothing traps.
    let sPlusL : Blob = "\4c\8c\78\72\aa\06\4e\04\9d\bb\30\13\fb\f2\93\80\d2\5b\f5\f0\59\5b\be\24\65\51\41\43\8e\7a\10\1b";
    assert not verify(cat(b(rOf(sig)), sPlusL), msg, pub);
  });
  test("S = L and S = 2^256 - 1 are refused without trapping", func() {
    assert not verify(cat(b(rOf(sig)), sEqL), msg, pub);
    assert not verify(cat(b(rOf(sig)), sMax), msg, pub);
  });
  test("bad A: off-curve, negative zero, y = p, y = 2^255 - 1", func() {
    for (a in [offCurve, negZero, yEqP, yMax].vals()) { assert not verify(sig, msg, a) };
  });
  test("bad R: off-curve, negative zero, y = p, y = 2^255 - 1", func() {
    for (r in [offCurve, negZero, yEqP, yMax].vals()) { assert not verify(cat(r, b(sOf(sig))), msg, pub) };
  });
  test("flipping one bit in every 8th signature byte is refused", func() {
    let bytes = Blob.toArray(sig);
    var i = 0;
    while (i < 64) {
      let flipped = Array.tabulate<Nat8>(64, func(j) = if (j == i) bytes[j] ^ 0x01 else bytes[j]);
      assert not verify(Blob.fromArray(flipped), msg, pub);
      i += 8; // every 8th byte keeps the suite fast; the differential covers the rest
    };
  });
});
